# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

workspace 'IntroViewDemo'

project 'IntroViewDemo'

use_frameworks!

target 'IntroViewDemo' do
    project 'IntroViewDemo'
    pod 'KDIntroView', :git => 'https://github.com/AppDevGuy/KDIntroView'
end

